export default {
    GET_MESSAGES: 'GET_MESSAGES',
    NEW_MESSAGE: 'NEW_MESSAGE',
    POST_MESSAGE: 'POST_MESSAGE',
    GET_SPACES: 'GET_SPACES',
    GET_CHANNELS: 'GET_CHANNELS',
    USER_SIGNUP: 'USER_SIGNUP',
    USER_LOGIN: 'USER_LOGIN',
    AUTH_ERROR: 'AUTH_ERROR',
    USER_LOGOUT: 'USER_LOGOUT',
    FETCHED_SPACES: 'FETCHED_SPACES',
    FETCHED_SPACE_MESSAGES: 'FETCHED_SPACE_MESSAGES'
}